### ISSUE TITLE
adduser するときのパスワード強度チェック

### ISSUE THREAD

**Issue by t-uda** [kmc-jp/guildbook#23]
* パスワードに使える文字セットは `[!-~]`
* 8文字以上
* 「数字」「小文字」「大文字」「記号」の中から3種類以上組み合わせていること

**Comment by hanazuki** [comment]
\x20もいれてあげて！

**Comment by t-uda** [comment]
確かに．

（`kmcadduser` のをそのまま参考にしてたけど確かに使えてほしい）

**Comment by tyage** [comment]
`\x20-\x7e` で実装します

**Comment by t-uda** [comment]
![](http://nojima.kmc.jp/imagia/e07808be07bb87d84c3f17fcfd5f897364ae9adb.png)
![](http://nojima.kmc.jp/imagia/0dbbb2ff4958d0003bf78531cb8056d0a9d85d20.png)
![](http://nojima.kmc.jp/imagia/6d6bafa0422d9129f9f71d56eeb311e5ff56ae60.png)
