### ISSUE TITLE
ユーザー登録で打ってる途中で､「弱いパスワード」とか出してほしい｡

### ISSUE THREAD

**Issue by nna774** [kmc-jp/guildbook#25]
js で判定されて赤くなったり緑になったりするやつ｡

**Comment by tyage** [comment]
invalidなパスワードだったら赤色で、submitボタンがdisabledになるとかでよさそう

**Comment by nna774** [comment]
弱い！！！ ってでかでかと出てほしい｡

**Comment by tyage** [comment]
あと確認用パスワードとの一致も出さないとやな

**Comment by t-uda** [comment]
この辺を取り入れようかと思ってます：

- https://css-tricks.com/password-strength-meter/
- https://github.com/dropbox/zxcvbn

何か良いライブラリ案があったら教えてくれ〜〜〜〜

**Comment by tyage** [comment]
yosasou

**Comment by pastak** [comment]
https://github.com/dropbox/zxcvbn 使ってる
