### ISSUE TITLE
ユーザー名バリデーション

### ISSUE THREAD

**Issue by tyage** [kmc-jp/guildbook#26]
kmcadduserにある以下が足りてないように見える...？

```perl
if ! echo -n "$loginname" | egrep -q "^[a-z][a-z0-9]{2,7}$"; then
    echo "ERROR: You cannot use id $loginname : invalid format" >&2
    exit -1
fi
```

**Comment by t-uda** [comment]
あー ホントですねぇ．やります．

**Comment by t-uda** [comment]
![](http://nojima.kmc.jp/imagia/1cec2763d98f39cfea0fe2430c1ef1dd0607262b.png)
![](http://nojima.kmc.jp/imagia/2e489f2634df08a36e46d17586c5cb9b6791f087.png)

**Comment by tyage** [comment]
[![LGTM](http://www.lgtm.in/p/OFSshQ75q)](http://www.lgtm.in/i/OFSshQ75q)

[:+1:](http://www.lgtm.in/u/OFSshQ75q) [:-1:](http://www.lgtm.in/r/OFSshQ75q)

**Comment by hanazuki** [comment]
アカウント名は3文字以上でおねがいします．
