### ISSUE TITLE
adduser 時の正常書き込み成功確認

### ISSUE THREAD

**Issue by t-uda** [kmc-jp/guildbook#33]
現状，権限がないユーザで新規ユーザを作成しようとすると `Insufficient Access` のエラーにはなるが，分かりづらい．

きちんと事前に bind するユーザが admin に属することを確認するようにし，admin でなければエラーメッセージを表示したい．

**Comment by hanazuki** [comment]
どのユーザがLDAPエントリを追加しうるかというのはGuildbookの知るところではないので，実際にエントリ追加を試してみてダメだった時のエラーメッセージを工夫するとかで対処するのが正しいありかたではないでしょうか．

**Comment by t-uda** [comment]
そうなんですけど，`Net::LDAP` がそういう例外を投げてくれないので，それをやろうと思うと
```ruby
if conn.get_operation_result.message == 'Insufficient Access Rights'
  raise ...
end
```
ってなる気がします．

**Comment by hanazuki** [comment]
`conn.get_operation_result.code` はどうでしょう？ LDAPの規格で決まっているはずのエラーコードが得られませんか

**Comment by t-uda** [comment]
あぁ，なるほど．50 番か見ればいいですね．
