### ISSUE TITLE
各種プラグインの使い方をわかりやすく！！！

### ISSUE THREAD

**Issue by t-uda** [kmc-jp/guildbook#36]
ハンドブックへのリンクを張るとかなんかしたい？

adduser の方みたいに上のメニューから選択できるようにしてもいいのかもしれない．（ホンマか

**Comment by hanazuki** [comment]
関連: #37

**Comment by t-uda** [comment]
* [ ] ヘルプページを書きましょう．単に [解説記事/ネットワーク/内部Web/GuildBook](https://inside.kmc.gr.jp/rubwiki/%E8%A7%A3%E8%AA%AC%E8%A8%98%E4%BA%8B/%E3%83%8D%E3%83%83%E3%83%88%E3%83%AF%E3%83%BC%E3%82%AF/%E5%86%85%E9%83%A8Web/GuildBook) で良さそう？（必要なら追記する感じで）
* [ ] config に `help_uri` を書いて deploy してください～～～～～
