### ISSUE TITLE
.forward の設定させるの大変だし、登録フォームにメール欄追加してそこに書かれた内容で.forward 生成してはどうか。

### ISSUE THREAD

**Issue by nna774** [kmc-jp/guildbook#44]
ご意見募集したいところ。

`nano` の使い方を何回も説明するのは飽きたんじゃ。

**Comment by t-uda** [comment]
`.forward` 生成は誰の権限でやるんでしょうか．

**Comment by nna774** [comment]
あーたしかに？

じゃあたとえば
`.forward` の中身を以下の内容で上書きするフォーム みたいなのを名簿の編集画面に追加する。 とかはどうでしょう。

**Comment by nna774** [comment]
とにかく、 ssh で入ってnanoで編集 っていうのを何とかしたい気持ちが根底にあります。

**Comment by hanazuki** [comment]
それ，`.forward`をglobal-writableにしないと実現できなくないですか．

postfixの設定で転送先アドレスをLDAPからも引くようにはできると思う．

**Comment by nna774** [comment]
あれ 名簿の編集って編集する人の権限で動いてなかったですっけ。

たしかに LDAP に転送先を入れるのが一番いいのかな って気はする。

**Comment by nna774** [comment]
あっ あれは編集する人の権限とは言っても、LDAPの認証か。

**Comment by t-uda** [comment]
うぇぶあぷりけーしょんやで～＾～～

私もやっぱり LDAP から転送先アドレス引けるようにすればいいと思うんですよ……
https://github.com/kmc-jp/box2-servers/issues/50

**Comment by t-uda** [comment]
転送は kmc-jp/box2-servers#50 のほうでやる機運なので，あとは `x-kmc-MailForwardingAddress` の編集フォームだけ作ればいいですね．（この issue は wontfix 的なので閉じて編集フォームは新しい issue にしましょう？）

**Comment by nna774** [comment]
賛成です。
