### ISSUE TITLE
宴会用リストにかなり昔に居なくなった人が出てしまう

### ISSUE THREAD

**Issue by siotouto** [kmc-jp/guildbook#76]
居なくなった人がずっと宴会用リストにたまり続けていて邪魔。
(今はさほどでもないけれど、これは新名簿がまだ大きくないから)
居なくなった人(具体的には新年度で名簿を更新していない学生)の行を
コメントアウトかそもそも出力しないようにしたいです。

**Comment by siotouto** [comment]
` ::GuildBook::UnivHelper.outdated?(u) ` を流用することでできるのかな、
と思うのですがイマイチ使い方はわかってないです

**Comment by hanazuki** [comment]
当初実装したときは、アカウント凍結処理をするとチェックリストにもでなくなるのでいいかなーと思ってた。

**Comment by siotouto** [comment]
あれ、凍結がなされてないからゴミが溜まってるだけだったりしますかもしかして

**Comment by siotouto** [comment]
邪魔なことではなく、本人のあるべきところにないことが不便な気もするし
年度の変わり目以降に更新されていない学生("現在の"提出名簿と同じ基準)はコメントアウトされる方針なのは問題なさそうかな...
